## Objective: Learning to solve basic Python problems

Prerequisites: Module 1 listed @ https://www.appliedaicourse.com/course/11/Applied-Machine-learning-course - SQL

Tackle few simple problems relvant to AI/ML
    - Break a problem into smaller sub-problems.
    - Connecting the dots from sub-problems to coding-concepts.
    - Code-walkthrough + Putting it all together.
    - More focus on common errors and mistakes + reading function reference + fixing bugs
    - Exercise-problems for practice.
    - Introduce new concepts as we need.
    - Good programmers may not benifit much from this session.
    

### Problem 1: Add two randomly generated NumPy matrices using loops 
    - Sub-problems
    - Subproblems ---> coding concepts
    - Code-walkthrough + Mistakes
    - Exercise: Add two randomly generated NumPy 3D-matrices(tensor) using loops 

In [1]:
import numpy as np

In [26]:
a = np.random.randint(2,30,(5,4)) # (low, high, size) 
print(a.shape,a)

(5, 4) [[17 13 25 12]
 [ 6  4  2 18]
 [21  3 20  7]
 [14  6 21 24]
 [14 24 14 20]]


In [10]:
# create random matrix A1 of size 5X4.
### Google " numpy create random matrices " & Read through the top 4-5 links
### https://www.codespeedy.com/how-to-create-matrix-of-random-numbers-in-python-numpy/

import numpy as np
A1 = np.random.rand(5,4) # read documentation to understand the params. Google "np.random.rand reference" ---> https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.random.rand.html

##COMMON-ERROR: np.random.rand(4,5)
##COMMON_ERROR: 

print(A1) # always print to ensure that everyhitng works fine.

print(A1.shape)


[[0.64546128 0.8718109  0.18202639 0.56190672]
 [0.03266979 0.85249758 0.01147952 0.37241042]
 [0.22954054 0.6392529  0.70471956 0.21240528]
 [0.70648775 0.55751517 0.31079812 0.52128958]
 [0.75316191 0.83577774 0.75551244 0.71560597]]
(5, 4)


In [11]:
print(A1.shape()); #COMMON-ERROR

TypeError: 'tuple' object is not callable

In [12]:
print(A1.type); # COMMON-ERROR

AttributeError: 'numpy.ndarray' object has no attribute 'type'

In [13]:
print(type(A1));

<class 'numpy.ndarray'>


In [0]:
# Read through the attributes and methods in numpy.ndarray class
## Google "numpy.ndarray" ---> https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.html

## Pre-Google programmers: Read reference docs.

In [17]:
# Create random Matrix A2
A2 = np.random.rand(5,4);
b = np.random.randint(low=2,high=60,size=(5,4))
print(b)
print(A2);

[[22 15 56 25]
 [27 57 44 23]
 [29 42 43 14]
 [34 33 10 54]
 [28 50 40  2]]
[[0.49769703 0.9970804  0.08016644 0.27135422]
 [0.34564452 0.64565172 0.37097523 0.1958945 ]
 [0.64524728 0.64846896 0.1595673  0.45980501]
 [0.43060372 0.75071715 0.52137207 0.40003999]
 [0.74184762 0.56550501 0.51784053 0.39543841]]


In [15]:
# Add element wise using loops A1+A2 = B

## Google "Accessing i,j th element in an ndarray" ---> https://docs.scipy.org/doc/numpy/reference/arrays.ndarray.html
print(A1[2,3]);


0.21240527792418584


In [18]:
print(A1(2,3)); #COMMON_ERROR

TypeError: 'numpy.ndarray' object is not callable

In [19]:
print(a[(2,3)])

29


In [0]:
B= A1+A2; # using + operator on ndarrays
print(B); 

[[1.23485298 1.03929117 1.4531507  0.63221396]
 [1.29876635 0.51588998 0.75634747 0.97533932]
 [1.86193091 0.75818597 1.35644263 0.75813984]
 [0.99238733 1.35895577 0.87935241 1.48757843]
 [1.10696065 0.45694659 0.69490656 0.52769753]]


In [27]:
c = np.zeros((5,4))
print()
c = a+b
print(a,b,c)
for i in range(5):
    print(i)
    

[[17 13 25 12]
 [ 6  4  2 18]
 [21  3 20  7]
 [14  6 21 24]
 [14 24 14 20]] [[22 15 56 25]
 [27 57 44 23]
 [29 42 43 14]
 [34 33 10 54]
 [28 50 40  2]] [[39 28 81 37]
 [33 61 46 41]
 [50 45 63 21]
 [48 39 31 78]
 [42 74 54 22]]
0
1
2
3
4


In [28]:
(r,c) = a.shape;
print(r,c)

5 4


In [0]:
#B[i,j] = A1[i,j] + A2 [i,j] 

for i in range(r):
    for j in range(c):
        B[i,j] = A1[i,j] + A2[i,j];
        
print(B)

[[1.23485298 1.03929117 1.4531507  0.63221396]
 [1.29876635 0.51588998 0.75634747 0.97533932]
 [1.86193091 0.75818597 1.35644263 0.75813984]
 [0.99238733 1.35895577 0.87935241 1.48757843]
 [1.10696065 0.45694659 0.69490656 0.52769753]]


In [33]:
c =np.zeros(shape=(5,4),dtype=int)
c

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [35]:
row,col = a.shape
for i in range(row):
    for j in range(col):
        c[i,j] = a[i,j] + b[i,j]
print(c)

[[39 28 81 37]
 [33 61 46 41]
 [50 45 63 21]
 [48 39 31 78]
 [42 74 54 22]]


In [0]:
# OPTIMIZATION: Pre-allocate matrix B
B = np.zeros(5,4); # COMMON-ERROR

TypeError: data type not understood

In [37]:
#Google "np.zeros" ---> https://docs.scipy.org/doc/numpy/reference/generated/numpy.zeros.html
B = np.zeros((5,4))

for i in range(row): # same code as earlier
    for j in range(col):
        B[i,j] = A1[i,j] + A2[i,j];
        
print(B)

[[1.1431583  1.8688913  0.26219283 0.83326094]
 [0.37831431 1.4981493  0.38245475 0.56830492]
 [0.87478782 1.28772186 0.86428686 0.67221029]
 [1.13709147 1.30823232 0.83217019 0.92132957]
 [1.49500953 1.40128275 1.27335297 1.11104438]]


In [39]:
# Time Complexity: ?         O(r*c) or O(n*2)
# Space Complxiety: ?        O(1) Because A1,A2,B are input and output which does not include in space complexity
#                            but we have i,j,row,col which will include in space complexity, therefore, complexity is constant
    

#### Exercise: Add two randomly generated NumPy 3D-matrices(tensor) using loops 

HINT: B[i,j,k] = A1[i,j,k] + A2[i,j,k]
****************************************************************************************************************
****************************************************************************************************************
****************************************************************************************************************

In [40]:
A1 = np.random.randint(low=2, high=60,size=(3,3,3))
A2 = np.random.randint(low=2, high=60,size=(3,3,3))
B = np.zeros(shape=(3,3,3) , dtype = int)

In [47]:
r,c,h= A1.shape
print("{}\n\n\n\n{}\n\n\n\n{}".format(A1,A2,B))

[[[52 48 26]
  [ 3 15 16]
  [ 3  3 24]]

 [[18 42 55]
  [50 51 46]
  [44 22 23]]

 [[19 25 21]
  [37 42 57]
  [43 57 35]]]



[[[ 3 20 43]
  [13 21 40]
  [12 18 16]]

 [[ 2 52  6]
  [10 16  8]
  [49  6 26]]

 [[36 39 20]
  [33 49 39]
  [51 58 47]]]



[[[ 55  68  69]
  [ 16  36  56]
  [ 15  21  40]]

 [[ 20  94  61]
  [ 60  67  54]
  [ 93  28  49]]

 [[ 55  64  41]
  [ 70  91  96]
  [ 94 115  82]]]


In [43]:
for i in range(r):
    for j in range(c):
        for k in range(h):
            B[i,j,k] = A1[i,j,k] + A2[i,j,k]
print(B)

[[[ 55  68  69]
  [ 16  36  56]
  [ 15  21  40]]

 [[ 20  94  61]
  [ 60  67  54]
  [ 93  28  49]]

 [[ 55  64  41]
  [ 70  91  96]
  [ 94 115  82]]]


### Problem 2: Find if a given 2D-point is inside (or) outside a circle 
    - Subproblems.
    - Subproblems --> coding concepts.
    - putting it all together.
    - Exercise: Find if a given 2D point is inside (or) outside a rectangle ? 
   

In [65]:
## input circle (C) and point(P)

# input circle params
# Google " input multiple values python 3" ---> https://www.geeksforgeeks.org/input-multiple-values-user-one-line-python/
print("Enter Cx, Cy, r:");
(Cx, Cy, r) = raw_input().split();
print(type(Cx))

print(Cx, Cy, r); # always cross check using print statements

Enter Cx, Cy, r:


NameError: name 'raw_input' is not defined

In [66]:
# Google " SyntaxError: invalid syntax input Python3 string" --> https://stackoverflow.com/questions/25174925/syntax-error-for-input
Cx, Cy, r = raw_input("Enter Cx, Cy, r:").split();


NameError: name 'raw_input' is not defined

In [84]:
# input circle params
## Google "python input multiple values in single line" ----> https://www.tutorialspoint.com/how-to-input-multiple-values-from-user-in-one-line-in-python
## TRY MULTIPLE APPROACHES and learn from each attempt.

Cx, Cy, r = input("Enter Cx, Cy, r:").split();


Enter Cx, Cy, r:0 0 5


In [85]:
print(Cx, Cy,r)
Cx = float(Cx) ; Cy = float(Cy) ; r = float(r) 

0 0 5


In [100]:
# Input Px, Py
print(type(r))
Px, Py = input("Enter Px, Py:").split()
print(Px, Py)
Px=float(Px) ; Py = float(Py)

<class 'float'>
Enter Px, Py:3 4
3 4


In [101]:
# Check if P lies in C.
d = (( (Cx-Px)**2 + (Cy-Py)**2 ) )**.5
print(d);

if d<r:
    print("Point is in Circle")
elif d==r:
    print("Point on the Circle")
else:
    print("Point is not in Circle")

5.0
Point on the Circle


In [0]:
# Check if P lies in C.

## String to Float. Very important to note that split() returns Strings
Cx = float(Cx);
Cy = float(Cy);
r =float(r);
Px= float(Px);
Py = float(Py);

import math 

d = math.sqrt( (Cx-Px)**2 + (Cy-Py)**2 )
print(d);

if d<r:
    print("P in C")
else:
    print("P NOT in C")

1.41421356237
P in C


In [106]:
cx,cy,r = map(float,input("Enter value for Cx Cy R : ").split())

Enter value for Cx Cy R : 0 0 5


In [108]:
import math 

d = math.sqrt( (Cx-Px)**2 + (Cy-Py)**2 )
print(d);

if d<r:
    print("Point is in Circle")
elif d==r:
    print("Point on the Circle")
else:
    print("Point is not in Circle")

5.0
Point on the Circle


#### Exercise: Find if a point is inside or outside a rectangle.

HINT: How do you represent a rectangle?

********************************************
********************************************
********************************************

In [2]:
Tx,Ty,Bx,By = map(float,input("Enter diagonal Points (Tx,Ty) and (Bx,By): ").split())

Enter diagonal Points (Tx,Ty) and (Bx,By): 1 5 5 1


In [4]:
Px,Py = map(float,input("Enter Point: ").split()) 

Enter Point: 2 2


In [5]:
if Tx < Px < Bx  and Ty > Py > By:
    print("Inside")
else:
    print("Outside")

Inside


### Problem 3: NumPy ndarray manupualtion operations


In [6]:
# 1. Reshape matrices: Very COMMON-ERRORS in Assignments
A = np.random.rand(5,4);
print(A);


[[0.5591771  0.06306177 0.36026725 0.59489795]
 [0.23274691 0.6995814  0.10718379 0.03482812]
 [0.26737534 0.63604881 0.47299799 0.61558204]
 [0.83064338 0.44282469 0.17617097 0.47070315]
 [0.72193478 0.5449578  0.57856609 0.13507701]]


In [0]:
## reshape into a vector row-major-order
###https://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html 
### Patiently read the documentation and try alternaive params
print( np.reshape(A, 20, 'C'))


[0.14807421 0.76465119 0.35072274 0.44772859 0.76310969 0.60355746
 0.39205106 0.55551216 0.52171983 0.14015325 0.07435462 0.84967035
 0.31052941 0.57171621 0.36938534 0.92015166 0.14458459 0.12976042
 0.4790811  0.98251111]


In [13]:
a = np.array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
#Row Major Order   or   C-like index order
np.reshape(a,newshape= -1,order='C')

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
#Coloum Major Order   or   Fortran-like index order
np.reshape(a,newshape= -1,order='F')

array([1, 4, 7, 2, 5, 8, 3, 6, 9])

In [27]:
b=np.random.randint(50,size=(5,4))

In [28]:
b

array([[16,  2, 20,  1],
       [46, 13, 33, 41],
       [42,  6, 38, 15],
       [13, 25, 23, 28],
       [16, 43, 30, 44]])

In [30]:
np.reshape(b,newshape=(2,-1),order='C')

array([[16,  2, 20,  1, 46, 13, 33, 41, 42,  6],
       [38, 15, 13, 25, 23, 28, 16, 43, 30, 44]])

In [31]:
np.reshape(b,newshape=(2,-1),order='F')

array([[16, 42, 16, 13, 25, 20, 38, 30, 41, 28],
       [46, 13,  2,  6, 43, 33, 23,  1, 15, 44]])

In [32]:
np.reshape(b,newshape=(-1,5),order='C')

array([[16,  2, 20,  1, 46],
       [13, 33, 41, 42,  6],
       [38, 15, 13, 25, 23],
       [28, 16, 43, 30, 44]])

In [22]:
print( np.reshape(A, 20, 'F'))

[0.5591771  0.23274691 0.26737534 0.83064338 0.72193478 0.06306177
 0.6995814  0.63604881 0.44282469 0.5449578  0.36026725 0.10718379
 0.47299799 0.17617097 0.57856609 0.59489795 0.03482812 0.61558204
 0.47070315 0.13507701]


In [23]:
print( np.reshape(A, (4,5), 'C'))

[[0.5591771  0.06306177 0.36026725 0.59489795 0.23274691]
 [0.6995814  0.10718379 0.03482812 0.26737534 0.63604881]
 [0.47299799 0.61558204 0.83064338 0.44282469 0.17617097]
 [0.47070315 0.72193478 0.5449578  0.57856609 0.13507701]]


In [24]:
print( np.reshape(A, (4,-1), 'C'))

[[0.5591771  0.06306177 0.36026725 0.59489795 0.23274691]
 [0.6995814  0.10718379 0.03482812 0.26737534 0.63604881]
 [0.47299799 0.61558204 0.83064338 0.44282469 0.17617097]
 [0.47070315 0.72193478 0.5449578  0.57856609 0.13507701]]


In [25]:
print( np.reshape(A, (-1,5), 'C'))

[[0.5591771  0.06306177 0.36026725 0.59489795 0.23274691]
 [0.6995814  0.10718379 0.03482812 0.26737534 0.63604881]
 [0.47299799 0.61558204 0.83064338 0.44282469 0.17617097]
 [0.47070315 0.72193478 0.5449578  0.57856609 0.13507701]]


In [21]:
print( np.reshape(A, (4,6), 'C'))

ValueError: cannot reshape array of size 20 into shape (4,6)

#### Exercise: take a tensor of size 4X5X6 and convert it into a tensor of vector and matrix (10X12).

In [38]:
#2. Stacking
A = np.random.rand(5,4);
print(A);

B= np.random.rand(5,2);
print(B)


[[0.31388792 0.72640318 0.1961676  0.52129271]
 [0.31218072 0.37889884 0.56676805 0.62125486]
 [0.05850966 0.60062785 0.83445378 0.31115639]
 [0.22213152 0.58969813 0.40583255 0.45673799]
 [0.00462413 0.77503122 0.8569852  0.84287912]]
[[0.29924029 0.24816216]
 [0.53129367 0.31064457]
 [0.21662511 0.57143481]
 [0.80148723 0.28776961]
 [0.00150689 0.7154128 ]]


In [39]:
# C = [A B]
C = np.hstack(A, B);
print(C)

TypeError: hstack() takes 1 positional argument but 2 were given

In [40]:
C = np.hstack((A, B)); # read documentation carefully
print(C)

[[0.31388792 0.72640318 0.1961676  0.52129271 0.29924029 0.24816216]
 [0.31218072 0.37889884 0.56676805 0.62125486 0.53129367 0.31064457]
 [0.05850966 0.60062785 0.83445378 0.31115639 0.21662511 0.57143481]
 [0.22213152 0.58969813 0.40583255 0.45673799 0.80148723 0.28776961]
 [0.00462413 0.77503122 0.8569852  0.84287912 0.00150689 0.7154128 ]]


In [0]:
A = np.random.rand(5,4);
print(A);

B= np.random.rand(4,4);
print(B)

C = np.hstack((A, B));
print(C)

[[0.07442156 0.90842643 0.26791901 0.52103986]
 [0.31627629 0.96720084 0.92801681 0.29094456]
 [0.92762484 0.2036012  0.62790382 0.21155578]
 [0.03114235 0.02227744 0.45126548 0.07824812]
 [0.31206675 0.12787428 0.78704942 0.95472092]]
[[0.74204087 0.3375716  0.53499921 0.64780102]
 [0.95762786 0.35441587 0.99187725 0.38097213]
 [0.34547302 0.48853482 0.85121261 0.81847693]
 [0.1783305  0.40696326 0.71089858 0.49241374]]


ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [0]:
A = np.random.rand(5,4);
print(A);

B= np.random.rand(4,4);
print(B)

C = np.vstack((A, B)); #Vertical stacking
print(C)

[[0.47572417 0.88468831 0.81030914 0.54286827]
 [0.088576   0.6447609  0.65370572 0.31849572]
 [0.01805613 0.46166837 0.4602457  0.35788657]
 [0.37245741 0.49461568 0.31431636 0.3799997 ]
 [0.96098487 0.1608441  0.50098802 0.01518362]]
[[0.43308702 0.04543804 0.91316269 0.86101818]
 [0.86514807 0.63395249 0.40368305 0.31388662]
 [0.82764524 0.15498427 0.70440415 0.904619  ]
 [0.13671617 0.81722549 0.95948317 0.70652946]]
[[0.47572417 0.88468831 0.81030914 0.54286827]
 [0.088576   0.6447609  0.65370572 0.31849572]
 [0.01805613 0.46166837 0.4602457  0.35788657]
 [0.37245741 0.49461568 0.31431636 0.3799997 ]
 [0.96098487 0.1608441  0.50098802 0.01518362]
 [0.43308702 0.04543804 0.91316269 0.86101818]
 [0.86514807 0.63395249 0.40368305 0.31388662]
 [0.82764524 0.15498427 0.70440415 0.904619  ]
 [0.13671617 0.81722549 0.95948317 0.70652946]]


In [0]:
# 3D tensors
A = np.random.rand(5,4,3); # (height, width, colors) in images is a good way to think of this
print(A.shape);

B= np.random.rand(5,3,3);
print(B.shape)

C = np.hstack((A, B));
print(C.shape)

(5, 4, 3)
(5, 3, 3)
(5, 7, 3)


In [0]:
# 3D tensors
A = np.random.rand(5,4,3);
print(A.shape);

B= np.random.rand(4,3,3);
print(B.shape)

C = np.hstack((A, B));
print(C.shape)

(5, 4, 3)
(4, 3, 3)


ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [0]:
# 3D tensors
A = np.random.rand(5,4,3);
print(A.shape);

B= np.random.rand(5,4,2);
print(B.shape)

C = np.hstack((A, B));
print(C.shape)

(5, 4, 3)
(5, 4, 2)


ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [0]:
# 3D tensors vstack
A = np.random.rand(5,4,3); # (height, width, colors) in images
print(A.shape);

B= np.random.rand(2,4,3);
print(B.shape)

C = np.vstack((A, B));
print(C.shape)

(5, 4, 3)
(2, 4, 3)
(7, 4, 3)


#### Exercise: Achieve the above tranaomfrs using numpy.concatenate [https://numpy.org/doc/1.18/reference/generated/numpy.concatenate.html#numpy.concatenate]
***********
***********
***********
***********


### Problem-4: Find peaks/max in an list
- problem definition


In [0]:

A = [1,3,4,5,7,6,4,5,10,1];
print(A)

[1, 3, 4, 5, 7, 6, 4, 5, 10, 1]


In [0]:
# Peaks: 7,10
# Peak: A[i-1] <= A[i] >= A[i+1]

for i in range(1, A.size - 1): # 1 and -1 are important
    if (A[i] >= A[i-1]) and (A[i] >= A[i+1]):
        print(A[i]);

AttributeError: 'list' object has no attribute 'size'

In [0]:
print(len(A));

10


In [0]:
for i in range(1, len(A) - 1): # 1 and -1 are important
    if (A[i] >= A[i-1]) and (A[i] >= A[i+1]):
        print(A[i]);

7
10


In [0]:
# There is a bug in the above solution. Find it...


In [0]:
A = [11,3,4,5,7,6,4,5,10,15];

for i in range(1, len(A) - 1): # 1 and -1 are important
    if (A[i] >= A[i-1]) and (A[i] >= A[i+1]):
        print(A[i]);

7


In [0]:
# what about 11 and 15?

# boundary case
if A[0] >= A[1]:
    print(A[0])
    
for i in range(1, len(A) - 1): # 1 and -1 are important
    if (A[i] >= A[i-1]) and (A[i] >= A[i+1]):
        print(A[i]);

# boundary case
if A[len(A)-1] >= A[len(A)-2]:
    print(A[len(A)-1])


In [0]:
# LESSON: Donot forget boundary cases

#Question: Time Complexity = ?

#### Exercise: 
1. Find peaks which are max values in a window of size 2 on both sides.
2. Use scipy.signal.find_peaks [https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.find_peaks.html]

Additioanl reading: More efficient algos @ http://courses.csail.mit.edu/6.006/spring11/lectures/lec02.pdf

### Problem 5: Permutations of a list
- Problem definition: lst = [1,2,3]

In [0]:
# Using libraries
from itertools import permutations 
  
p = permutations([1, 2, 3]) # refer: https://docs.python.org/3/library/itertools.html#itertools.permutations

# what is an iterable in Python [https://www.pythonlikeyoumeanit.com/Module2_EssentialsOfPython/Iterables.html]

# print the permutations
for i in list(p): 
    print i 

(1, 2, 3)
(1, 3, 2)
(2, 1, 3)
(2, 3, 1)
(3, 1, 2)
(3, 2, 1)


In [0]:
# No fun!
# Write your own code. Any suggestions?
# Break the problem into smaller sub-problems

In [0]:
[1,2,3]
[1,3,2]
[2,1,3]
[2,3,1]
[3,1,2]
[3,2,1]

[3, 2, 1]

In [0]:
# source: https://stackoverflow.com/questions/13109274/python-recursion-permutations

def permutation(s):
    if len(s) == 1:
        return [s]

    perm_list = [] # resulting list
    for a in s:
        remaining_elements = [x for x in s if x != a]
        z = permutation(remaining_elements) # permutations of sub-list

        for t in z:
            perm_list.append([a] + t)

    return perm_list

s = [1,2,3];
p = permutation(s);
print(p)

[[1, 2, 3], [1, 3, 2], [2, 1, 3], [2, 3, 1], [3, 1, 2], [3, 2, 1]]


#### Exercise: [Combinations] All possible ways to pick 3 elements out of 5 elements

- HINT: Use recursion.
- Google "combinations in Python"

### Practice, practice and practice..

- Optional  Assignments at AAIC: https://go.aws/2JrmV4A [Functions] , https://drive.google.com/file/d/1VB3wJSt_Mq0HLP9uaqgsZBR4BLMFnkmY/view [Pandas]

- Basic Python: https://www.geeksforgeeks.org/python-programming-examples/
- NumPy: https://www.w3resource.com/python-exercises/numpy/index.php


In [42]:
a=5
b=10

In [46]:
for i in range(5):
    print(i,end="")

01234